#!/bin/sh
#
# PROVIDE: goprogram
# REQUIRE: networking
# KEYWORD: 
 
. /etc/rc.subr
 
name="l2-server-game"
rcvar="l2game_enable"
folder="/usr/local/l2-server/game/"
goprogram_user="l2user"
pidfile=/var/run/${name}.pid
 
start_cmd="goprogram_start"
stop_cmd="goprogram_stop"
status_cmd="goprogram_status"

goprogram_start() {
	echo "${name} starting ..."
	cd ${folder}
	./GameServer_loop.sh ${pidfile} ${goprogram_user}
}

goprogram_stop() {
        if [ -e "${pidfile}" ]; then
                kill -s TERM `cat ${pidfile}`
		rm ${pidfile}
		echo "${name} stopped ..."
        else
                echo "${name} is not running"
        fi

}

goprogram_status() {
        if [ -e "${pidfile}" ]; then
                echo "${name} is running as pid `cat ${pidfile}`"
        else
                echo "${name} is not running"
        fi
}
 
load_rc_config $name
: ${goprogram_enable:=no}
 
run_rc_command "$1"

