#!/bin/sh
#
# PROVIDE: goprogram
# REQUIRE: networking
# KEYWORD: 
 
. /etc/rc.subr
 
name="l2rest"
rcvar="l2rest_enable"
folder="/home/andrew/l2-server-rest-0.0.1-SNAPSHOT"
goprogram_user="andrew"
pidfile="/var/run/${name}.pid"
 
start_cmd="goprogram_start"
stop_cmd="goprogram_stop"
status_cmd="goprogram_status"

goprogram_start() {
	echo "${name} starting ..."
	cd ${folder}
	./RestServer_loop.sh ${pidfile} "${goprogram_user}" 
}

goprogram_stop() {
        if [ -e "${pidfile}" ]; then
                kill -s TERM `cat ${pidfile}`
		rm ${pidfile}
		echo "${name} stopped ..."
        else
                echo "${name} is not running"
        fi

}

goprogram_status() {
        if [ -e "${pidfile}" ]; then
                echo "${name} is running as pid `cat ${pidfile}`"
        else
                echo "${name} is not running"
        fi
}
 
load_rc_config $name
: ${goprogram_enable:=no}
 
run_rc_command "$1"

