#!/bin/sh
#
# PROVIDE: goprogram
# REQUIRE: networking
# KEYWORD: 
. /etc/rc.subr
 
# Change the settings below for your needs:
# program name
name="l2rest"

goprogram_folder_name="l2-server-rest"

# variable for rc.conf
rcvar="l2rest_enable"

# user rights, with program will work 
goprogram_user="andrew"

# path to the program working folder
folder="/usr/home/${goprogram_user}/${goprogram_folder_name}"

# program PID file path
goprogram_pidfile="/usr/home/${goprogram_user}/${goprogram_folder_name}/run/${name}.txt"
 
start_cmd="goprogram_start"
stop_cmd="goprogram_stop"
status_cmd="goprogram_status"

goprogram_start() {
	echo "${name} starting ..."
	cd ${folder}
	./RestServer_loop.sh ${goprogram_user} ${goprogram_pidfile}
}

goprogram_stop() {
        if [ -e "${goprogram_pidfile}" ]; then
                kill -s TERM `cat ${goprogram_pidfile}`
		rm ${goprogram_pidfile}
		echo "${name} stopped ..."
        else
                echo "${name} is not running"
        fi

}

goprogram_status() {
        if [ -e "${goprogram_pidfile}" ]; then
                echo "${name} is running as pid `cat ${goprogram_pidfile}`"
        else
                echo "${name} is not running"
        fi
}
 
load_rc_config $name
: ${goprogram_enable:=no}
 
run_rc_command "$1"

